config/routes.rb
Rails.application.routes.draw do

  resources :questions

  root 'pages#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true, length: {minimum: 2}
    validates :body, presence: true, length: {minimum: 2}
  def formatted_created_at
     self.created_at.strftime('%Y-%m-%d %H:%M:%S')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def index
       @name = params[:name]
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def destroy
    @question = Question.find_by id: params[:id]
    @question.destroy
    redirect_to questions_path
  end

  def edit
    @question = Question.find_by id: params[:id]
  end

  def update
    @question = Question.find_by id: params[:id]
    if @question.update question_params
      redirect_to questions_path
    else
      render :edit
    end
  end

  def show
    @question = Question.find_by id: params[:id]
  end

  def index
     @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Test</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="nav-bar">
      <ul>
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Qestions", questions_path %></li>
      </ul>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/pages/index.html.erb
<h1><%= @name %>, Welcom to PHP</h2>

&copy; @bodrovis <%= Time.now.year %>

app/views/questions/_form.html.erb
<%= form_with model: @question do |f| %>
    <div>
        <%= f.label :title %>
        <%= f.text_field :title, required: true, minlength: 2, placeholder: "Title" %>
    </div>

    <div>
        <%= f.label :body %>
        <%= f.text_area :body, required: true, minlength: 2 %>
    </div>

    <%= f.submit "Submit question!" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit question</h1>

<%= render "form" %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<% @questions.each do |question| %>

  <div class="card_hom"> 
    <h2><%= question.title %></h2>
  
    <p> <%= question.body %> </p>

    <div class="time"><%= question.formatted_created_at %></div>
    
    <div class="crud_button">
      <div class="button_dit"> 
        <div class="text_link">
          <%= link_to 'Edit', edit_question_path(question) %> 
        </div>
      </div>
      <div class = "button_destroy">
        <div class="text_link">
            <%= link_to 'Destroy', question_path(question),method: :delete, data: { turbo_method: :delete }  %>
        </div>
      </div>
    </div>
  </div>
  
<% end %>

app/views/questions/new.html.erb
<h1>New Qestions</h1>

<%= render "form" %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h2>
<h3><%= @question.body %></h3>